export default {
  id: "fireworks",
  priority: 50,
  alias: "fireworks",
  display: {
    name: "Fireworks AI",
    icon: "local_fire_department",
    color: "#7B2EF2",
    textIcon: "FW",
    website: "https://fireworks.ai",
    notice: {
      apiKeyUrl: "https://fireworks.ai/account/api-keys",
    },
  },
  category: "apikey",
  authType: "apikey",
  thinkingConfig: { options: ["auto", "none", "low", "medium", "high", "max"], defaultMode: "auto" },
  transport: {
    baseUrl: "https://api.fireworks.ai/inference/v1/chat/completions",
    validateUrl: "https://api.fireworks.ai/inference/v1/models",
  },
  models: [
    { id: "accounts/fireworks/models/glm-5p2", name: "GLM 5.2" },
    { id: "accounts/fireworks/routers/glm-5p2-fast", name: "GLM 5.2 Fast" },
    { id: "accounts/fireworks/models/glm-5p1", name: "GLM 5.1" },
    { id: "accounts/fireworks/routers/glm-5p1-fast", name: "GLM 5.1 Fast" },
    { id: "accounts/fireworks/models/qwen3p7-plus", name: "Qwen 3.7 Plus" },
    { id: "accounts/fireworks/models/minimax-m3", name: "MiniMax-M3" },
    { id: "accounts/fireworks/models/minimax-m2p7", name: "MiniMax-M2.7" },
    { id: "accounts/fireworks/models/kimi-k2p7-code", name: "Kimi K2.7 Code" },
    { id: "accounts/fireworks/routers/kimi-k2p7-code-fast", name: "Kimi K2.7 Code Fast" },
    { id: "accounts/fireworks/models/kimi-k2p6", name: "Kimi K2.6" },
    { id: "accounts/fireworks/routers/kimi-k2p6-turbo", name: "Kimi K2.6 Turbo" },
    { id: "accounts/fireworks/routers/kimi-k2p6-fast", name: "Kimi K2.6 Fast" },
    { id: "accounts/fireworks/models/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "accounts/fireworks/models/gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "accounts/fireworks/models/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "accounts/fireworks/models/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "nomic-ai/nomic-embed-text-v1.5", name: "Nomic Embed Text v1.5", kind: "embedding" },
  ],
  serviceKinds: ["llm", "embedding"],
  embeddingConfig: { baseUrl: "https://api.fireworks.ai/inference/v1/embeddings" },
};
