export default {
  id: "zenmux-free",
  priority: 75,
  hasFree: true,
  alias: "zmf",
  aliases: ["zenmux", "zm"],
  uiAlias: "ZF",
  category: "free",
  authType: "cookie",
  authHint: "Paste ALL cookies from zenmux.ai as a raw Cookie header string after logging in.",
  display: {
    name: "ZenMux Free (Web)",
    icon: "bolt",
    color: "#667eea",
    textIcon: "ZF",
    website: "https://zenmux.ai",
    notice: {
      signupUrl: "https://zenmux.ai",
      note: "Uses free-tier session. Login at zenmux.ai, export all cookies (EditThisCookie / Cookie-Editor), paste the full cookie string. Refresh every ~30 days.",
    },
  },
  transport: {
    baseUrl: "https://zenmux.ai/api/anthropic/v1/messages",
    format: "openai",
    executor: "zenmux-free",
    noAuth: true,
    authType: "cookie",
  },
  models: [
    { id: "deepseek/deepseek-chat", name: "DeepSeek V3.2 (Non-thinking)" },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek V3.2 (Thinking)" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "kuaishou/kat-coder-pro-v1-free", name: "KAT Coder Pro V1 Free" },
    { id: "xiaomi/mimo-v2-flash-free", name: "MiMo V2 Flash Free" },
    { id: "z-ai/glm-4.7-flash-free", name: "GLM 4.7 Flash Free" },
    { id: "stepfun/step-3.5-flash-free", name: "Step 3.5 Flash Free" },
    { id: "inclusionai/ling-1t", name: "Ling 1T" },
    { id: "inclusionai/ling-mini-2.0", name: "Ling Mini 2.0" },
    { id: "inclusionai/ring-1t", name: "Ring 1T" },
    { id: "sapiens-ai/agnes-1.5-lite", name: "Agnes 1.5 Lite" },
    { id: "sapiens-ai/agnes-1.5-pro", name: "Agnes 1.5 Pro" },
  ],
  passthroughModels: true,
};
