// Database Models - Export all from localDb
export {
  getProviderConnections,
  getProviderConnectionById,
  createProviderConnection,
  updateProviderConnection,
  updateConnectionProxyPoolSnapshotIfBound,
  deleteProviderConnection,
  getProviderNodes,
  getProviderNodeById,
  createProviderNode,
  updateProviderNode,
  deleteProviderNode,
  deleteProviderNodeCascade,
  getProxyPools,
  getProxyPoolById,
  createProxyPool,
  updateProxyPool,
  updateProxyPoolWithBoundSnapshots,
  deleteProxyPool,
  deleteProviderConnectionsByProvider,
  getCombos,
  getComboById,
  getComboByName,
  createCombo,
  updateCombo,
  deleteCombo,
  getModelAliases,
  setModelAlias,
  deleteModelAlias,
  getCustomModels,
  addCustomModel,
  deleteCustomModel,
  getMitmAlias,
  setMitmAliasAll,
  getApiKeys,
  createApiKey,
  deleteApiKey,
  validateApiKey,
  isCloudEnabled,
  updateProviderStrategyProxyPoolSnapshotIfBound,
} from "@/lib/localDb";

// Seen models (New Models discovery)
export {
  getSeenModels,
  reconcileSeenModels,
  acknowledgeModels,
  countUnseenModels,
  seedSeenModels,
  getUnseenModels,
} from "@/lib/db/repos/seenModelsRepo.js";
